### ISSUE TITLE
Bug found on website

### ISSUE THREAD

**Issue by sanjay-kv** [sanjay-kv/Open-source-Practice#1056]
### Discussed in https://github.com/sanjay-kv/Open-source-Practice/discussions/1055

<div type='discussions-op-text'>

<sup>Originally posted by **sanjay-kv** September  8, 2024</sup>
in headline</div>

**Comment by Akanshaku** [comment]
I would like to work on this issue please assign me this @sanjay-kv

**Comment by sanjay-kv** [comment]
hey this i raised for training purpose
