### ISSUE TITLE
bug found on website

### ISSUE THREAD

**Issue by singhabhinendra** [sanjay-kv/Open-source-Practice#1146]
### Discussed in https://github.com/sanjay-kv/Open-source-Practice/discussions/1145

<div type='discussions-op-text'>

<sup>Originally posted by **singhabhinendra** October 14, 2024</sup>
In Headline</div>

**Comment by harshita2303** [comment]
Elaborate the bug

**Comment by Akanshaku** [comment]
If this is not yet done please assign me this @sanjay-kv

**Comment by sanjay-kv** [comment]
i dont think there is any website for this repo
