### ISSUE TITLE
Adding my name and Remove repeating name of P

### ISSUE THREAD

**Issue by Pushpa472** [sanjay-kv/Open-source-Practice#1172]
@sanjay-kv 
![image](https://github.com/user-attachments/assets/482ec1d1-9261-4d3b-b847-9c7a909621b1)

**Comment by Pushpa472** [comment]
@sanjay-kv Please also add hacktoberfest label

**Comment by sanjay-kv** [comment]
@Pushpa472 hacktoberfest cant be added to this repo, as this is beginner level, they wont accept basic pr

**Comment by Pushpa472** [comment]
ok
